version: '3'
services:
  # nosql-db:
  #   image: mvertes/alpine-mongo
  #   ports:
  #     - '27018:27017'
  #   container_name: nosql-db
  #   volumes:
  #     - ./db/:/data/db

  # rabbitmq:
  #   image: rabbitmq:alpine
  #   container_name: rabbitmq
  #   ports:
  #     - '5672:5672'

  courses:
    build:
      dockerfile: Dockerfile
      context: ./courses
    container_name: courses
    ports:
      - '7002:7002'
    restart: always
    # depends_on:
    #   - 'nosql-db'
    #   - 'rabbitmq'
    # volumes:
    #   - .:/app
    #   - /app/courses/node_modules
    # env_file:
    #   - ./courses/.env.dev

  graduation-tracking:
    build:
      dockerfile: Dockerfile
      context: ./graduation-tracking
    container_name: graduation-tracking
    ports:
      - '7003:7003'
    restart: always
    # depends_on:
    #   - 'nosql-db'
    #   - 'rabbitmq'
    # volumes:
    #   - .:/app
    #   - /app/graduation-tracking/node_modules
    # env_file:
    #   - ./graduation-tracking/.env.dev

  user:
    build:
      dockerfile: Dockerfile
      context: ./user
    container_name: user
    ports:
      - '7001:7001'
    restart: always
    # depends_on:
    #   - 'nosql-db'
    #   - 'rabbitmq'
    # volumes:
    #   - .:/app/
    #   - /app/user/node_modules
    # env_file:
    #   - ./user/.env.dev
