apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-deployment
  labels:
    app: courses
spec:
  replicas: 2
  selector:
    matchLabels:
      app: courses
  template:
    metadata:
      labels:
        app: courses
    spec:
      containers:
        - name: courses
          image: scholastic-planner-ms_courses
          imagePullPolicy: Never
          ports:
            - containerPort: 7002
---
apiVersion: v1
kind: Service
metadata:
  name: courses-service
spec:
  selector:
    app: courses
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7002
      targetPort: 7002
