apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: scholastic-planner-ms_user
          imagePullPolicy: Never
          ports:
            - containerPort: 7001
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001
